package tui

type commandInfo struct {
	Keys string
	Name string
	Help string
}

var commandCatalog = []commandInfo{
	{Keys: "q", Name: "quit", Help: "quit or close the current derived sheet"},
	{Keys: "Tab", Name: "sidebar", Help: "toggle the sheet-stack sidebar"},
	{Keys: "Enter", Name: "open-row", Help: "open the current row as a column/value table"},
	{Keys: "/", Name: "search", Help: "search for a case-insensitive substring"},
	{Keys: "c", Name: "goto-col-regex", Help: "search column names by regex and jump to the next match"},
	{Keys: "r", Name: "goto-row-regex", Help: "jump to the next row whose visible key matches a regex"},
	{Keys: "zc", Name: "goto-col-number", Help: "jump to a 0-based visible column number"},
	{Keys: "zr", Name: "goto-row-number", Help: "jump to a 0-based row number"},
	{Keys: "[", Name: "sort-asc", Help: "sort the current column ascending"},
	{Keys: "]", Name: "sort-desc", Help: "sort the current column descending"},
	{Keys: "=", Name: "expr-col", Help: "add a materialized expression column"},
	{Keys: "&", Name: "join", Help: "join with the previous sheet in the stack using the current column"},
	{Keys: "f", Name: "freeze", Help: "open a frozen snapshot of the current sheet"},
	{Keys: "v", Name: "graph", Help: "open a graph for the current column"},
	{Keys: "*", Name: "sparkline-col", Help: "add a sparkline column from visible numeric columns"},
	{Keys: "m", Name: "melt", Help: "open an unpivoted view using the current column as the identifier"},
	{Keys: "D", Name: "dedupe", Help: "open a deduplicated view using the current column"},
	{Keys: "F", Name: "frequency", Help: "open a frequency sheet for the current column"},
	{Keys: "I", Name: "describe", Help: "open a describe sheet for the current sheet"},
	{Keys: "W", Name: "pivot", Help: "open a pivot view grouped by the current column"},
	{Keys: "T", Name: "transpose", Help: "transpose the current sheet"},
	{Keys: "V", Name: "sheets", Help: "open the current sheet stack"},
	{Keys: "M", Name: "columns", Help: "open an editable columns metasheet"},
	{Keys: "O", Name: "options", Help: "open a viewer state sheet"},
	{Keys: "P", Name: "cmdlog", Help: "open the in-memory command log for this session"},
	{Keys: "?", Name: "commands", Help: "open the command reference"},
	{Keys: "R", Name: "redo", Help: "redo the last undone sheet mutation for the current sheet"},
	{Keys: "U", Name: "undo", Help: "undo the last sheet mutation for the current sheet"},
	{Keys: "zz", Name: "macro-record", Help: "start or stop recording a macro"},
	{Keys: "zZ", Name: "macro-play", Help: "replay the last recorded macro"},
	{Keys: "s", Name: "toggle-select", Help: "toggle selection on the current row"},
	{Keys: "t", Name: "select-all", Help: "select all rows"},
	{Keys: "u", Name: "clear-selection", Help: "clear all selected rows"},
	{Keys: "y", Name: "copy-cell", Help: "copy the current cell"},
	{Keys: "C", Name: "copy-rows", Help: "copy selected rows or the current row"},
	{Keys: "e", Name: "edit-cell", Help: "edit the current cell in place"},
	{Keys: "d", Name: "delete", Help: "delete selected rows or the current row"},
	{Keys: "S", Name: "save", Help: "save to a suggested export path"},
	{Keys: "-", Name: "hide-column", Help: "hide the current column"},
	{Keys: "H", Name: "show-all-columns", Help: "reveal all hidden columns"},
	{Keys: "^", Name: "rename-col", Help: "rename the current column"},
	{Keys: "_", Name: "resize-col", Help: "set the display width for the current column"},
	{Keys: "{", Name: "regex-capture", Help: "add capture-group columns from the current column"},
	{Keys: "}", Name: "regex-split", Help: "split the current column into multiple columns using a regex"},
	{Keys: "~", Name: "type-string", Help: "override the current column type to string"},
	{Keys: "#", Name: "type-int", Help: "override the current column type to int"},
	{Keys: "%", Name: "type-float", Help: "override the current column type to float"},
	{Keys: "$", Name: "type-currency", Help: "override the current column type to currency"},
	{Keys: "@", Name: "type-date", Help: "override the current column type to date"},
	{Keys: "|", Name: "regex-select", Help: "select rows matching a regex in the current column"},
	{Keys: "\\", Name: "regex-unselect", Help: "unselect rows matching a regex in the current column"},
	{Keys: ": / Ctrl+P", Name: "command-palette", Help: "open the command palette with fuzzy search"},
}

func controlHints() []string {
	return []string{
		"q quit",
		"Tab sidebar",
		"Enter open-row",
		"/ search",
		"c col-regex",
		"r row-regex",
		"zc/zr goto",
		"= expr-col",
		"& join",
		"f freeze",
		"v graph",
		"* spark",
		"m melt",
		"D dedupe",
		"F freq",
		"I describe",
		"W pivot",
		"T transpose",
		"V sheets",
		"M columns",
		"O options",
		"P cmdlog",
		"? commands",
		"R redo",
		"U undo",
		"zz/zZ macro",
		"y / C copy",
		"e edit-cell",
		"d delete",
		"S save",
		"- / H columns-visibility",
		"^ / _ columns-edit",
		"{ / } regex-cols",
		": palette",
	}
}
